### ISSUE TITLE
Geopaparazzi tile creater crash

### ISSUE THREAD

**Issue by tghoward** [moovida/hydrologis4gvsig#9]
Here's an error dump from an attempt to "create geopaparazzi tiles" from within gvSig:

ERROR java.lang.NullPointerException: null     org.hortonmachine.gvsig.geopaparazzi.GenerateTilesExtension.execute(GenerateTilesExtension.java:130)     org.gvsig.andami.actioninfo.impl.DefaultActionInfo.execute(DefaultActionInfo.java:307)     org.gvsig.andami.actioninfo.impl.DefaultActionInfo.actionPerformed(DefaultActionInfo.java:352)     javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)     javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)     javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)     javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)     javax.swing.AbstractButton.doClick(AbstractButton.java:376)     javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)     javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)     java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)     java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)     java.awt.Component.processMouseEvent(Component.java:6535)     javax.swing.JComponent.processMouseEvent(JComponent.java:3324)     java.awt.Component.processEvent(Component.java:6300)     java.awt.Container.processEvent(Container.java:2236)     java.awt.Component.dispatchEventImpl(Component.java:4891)     java.awt.Container.dispatchEventImpl(Container.java:2294)     java.awt.Component.dispatchEvent(Component.java:4713)     java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)     java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)     java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)     java.awt.Container.dispatchEventImpl(Container.java:2280)     java.awt.Window.dispatchEventImpl(Window.java:2750)     java.awt.Component.dispatchEvent(Component.java:4713)     java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)     java.awt.EventQueue.access$500(EventQueue.java:97)     java.awt.EventQueue$3.run(EventQueue.java:709)     java.awt.EventQueue$3.run(EventQueue.java:703)     java.security.AccessController.doPrivileged(Native Method)     java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)     java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)     java.awt.EventQueue$4.run(EventQueue.java:731)     java.awt.EventQueue$4.run(EventQueue.java:729)     java.security.AccessController.doPrivileged(Native Method)     java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)     java.awt.EventQueue.dispatchEvent(EventQueue.java:728)     org.gvsig.andami.ui.AndamiEventQueue.dispatchEvent(AndamiEventQueue.java:50)     java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)     java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)     java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)     java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)     java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)     java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

gvSIG version information:
gvSIG desktop
A Geographic Information System (GIS) for desktop environments  Version: 2.3.1-2501 final Java version: 1.8.0_73 © Copyright gvSIG Association. All rights reserved.

Horton machine version:

hydrologis4gvsig_0.2.0.gvspks

I'm very much new to gvSig so I likely have the basemaps set up in an unexpected way. I'm using a WMS service for a basemap which I want to make tiles for. 
 WMS info:

![image](https://user-images.githubusercontent.com/6129193/32384425-3ae6a5ee-c091-11e7-818b-1d5c723e1d48.png)

--Tim

**Comment by tghoward** [comment]
Better info on the basemap:

![image](https://user-images.githubusercontent.com/6129193/32384677-092963ec-c092-11e7-8bef-bf0887aeb827.png)

**Comment by moovida** [comment]
Hi @tghoward , I am afraid, this problem is due to the partial integration in gvSIG. At the moment the reading and writing is handled by the geotools libraries, while the map view is handled by gvSIG libraries. 
The WMS layers are not supported. 
But I agree that it should at least report that it is ignoring it and it should not explode.
I will look into it and report back.

**Comment by tghoward** [comment]
@moovida , ok, thanks. It would also be good to know what types of layers are supported.

**Comment by moovida** [comment]
This should now be fixe. Only certain filetypes are allowed.
